### ISSUE TITLE
OpenGL.error.GLError

### ISSUE THREAD

**Issue by liangshi036** [facebookresearch/eft#9]
when I run the demo visEFTFit.py , my parser definition is:

parser = argparse.ArgumentParser()
parser.add_argument('--img_dir',default="../demo/images/demo.png", type=str , help='Folder path where input image files exist')
parser.add_argument('--fit_data',default="../eft_fit/MPII_ver01.json", type=str, help='EFT data json fortmat')
parser.add_argument('--smpl_dir',default="../extradata/smpl", type=str , help='Folder path where smpl pkl files exist')
parser.add_argument('--onbbox',action="store_true", help="Show the 3D pose on bbox space")
parser.add_argument('--rendermode',default="geo", help="Choose among geo, normal, densepose")
parser.add_argument('--render_dir',default="render_eft", help="Folder to save rendered images")
parser.add_argument('--waitforkeys',action="store_true", help="If true, it will pasue after each visualizing each sample, waiting for any key pressed")
parser.add_argument('--turntable',action="store_true", help="If true, show turn table views")
parser.add_argument('--multi',action="store_true", help='If True, show all available fitting people per image. Default, visualize a single person at each time')
args = parser.parse_args()

I get error like this:

freeglut (foo): fgInitGL2: fghGenBuffers is NULL
Traceback (most recent call last):
  File "E:/human_pose_estimation/eft/demo/visEFTFit.py", line 436, in <module>
    renderer = getRenderer(args.rendermode)
  File "E:/human_pose_estimation/eft/demo/visEFTFit.py", line 52, in getRenderer
    renderer = meshRenderer.meshRenderer()
  File "E:\human_pose_estimation\eft\renderer\meshRenderer.py", line 37, in __init__
    glRenderer.__init__(self, width, height, name, 'geo', color_size, ms_rate)
  File "E:\human_pose_estimation\eft\renderer\glRenderer.py", line 34, in __init__
    glEnable(GL_DEPTH_CLAMP)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\OpenGL\platform\baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "src\errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
	err = 1280,
	description = b'\xce\xde\xd0\xa7\xc1\xd0\xbe\xd9',
	baseOperation = glEnable,
	cArguments = (GL_DEPTH_CLAMP,)
)

**Comment by jhugestar** [comment]
Are you using a virtual machine? I am not sure what causes this error. 

I just googled it and found:

https://stackoverflow.com/questions/33166936/freeglut-fginitgl2-fghgenbuffers-is-null/33722138

**Comment by liangshi036** [comment]
not virtual machine, I'm using :

Windows 10
cuda 10.1
PyOpenGL  3.1.5
PyOpenGL-accelerate  3.1.5
and other packages needed.

not sure  PyOpenGL is  working properly. 

so could you please offer the package version of the requirements?

**Comment by jhugestar** [comment]
Hmm, then I am not sure. We haven't tested this on windows machine. 

 I am using the following version for pyopengl. 

pyopengl                  3.1.0

I don't think cuda matters here.
